services:
  my-docker-claude-code:
    image: my-docker-claude-code:latest
    container_name: my-docker-claude-code
    volumes:
      # 挂载当前项目目录到容器工作空间
      - .:/workspace
      # 挂载用户Claude配置
      - ./.claude:/home/developer/.claude
      # 挂载SSH密钥（可选）
      - ./.ssh:/home/developer/.ssh:ro
      # 挂载Git配置
      - ./.gitconfig:/home/developer/.gitconfig:ro
      # 挂载npm缓存
      - npm_cache:/tmp/.npm
      # 挂载项目特定目录（根据需要）
      - ./projects:/workspace/projects
    environment:
      - HOME=/home/developer
      - USER=developer
    working_dir: /workspace
    stdin_open: true
    tty: true
    networks:
      - claude-network

volumes:
  npm_cache:
    driver: local

networks:
  claude-network:
    driver: bridge